### PR TITLE
Added a template hook that enables compile-time sketch exploration

### PR DESCRIPTION
**Pull request by noseglasses**
## Motivation

For some plugins it might be beneficial to gain information from the sketch to configure themselves based on the user's settings. For the static keymap being a PROGMEM array, this is already possible at runtime. However, iteratively traversing the static keymap at runtime, e.g. during plugin-setup, is both costly in terms of PROGMEM (code) and setup-runtime.

This is especially suboptimal as the static keymap's information is constant and, thus, known at compile time. With the consequence that any dependent type of information that is based on the static keymap alone could also be computed already at compile time.

Currently there's no infrastructure that allows that.

Following the above consideration, this PR introduces a new template hook that enables plugins to configure themselves conveniently by querying information through an also newly introduced sketch exploration API. The list of plugins, their order and occurrence can also be explored.

## Changes

* the keymap array was made `constexpr`
* general support for template hook methods was added
* a sketch exploration infrastructure was added (together with an example sketch in `examples/Internal/Sketch_Exploration`)

## Commits

This PR consists of three commits, two of which are independent 
* https://github.com/keyboardio/Kaleidoscope/commit/686044264e8815ffd1bf769e52e6ae6318753102
* https://github.com/keyboardio/Kaleidoscope/commit/7aa2c0e8596bd18412990067ebb5ee2ac6902f84

Those could be cherry picked in arbitrary order and have only been made part of this PR as the third commit (https://github.com/keyboardio/Kaleidoscope/pull/735/commits/8904b665ec85d5d140832ae1bd768287734e530d) depends upon them.

### CODE REVIEW

**Comment by noseglasses** [comment]
i pondered about this PR a bit further.

Now, as templated hooks are available, we could also make other types of compile time known information available that we can draw from the users' sketches, e.g. the registered plugins' types and their order of appearance.

Keymap exploration would then become sketch-exploration and we could replace the `KeymapInterface` class with a `SketchInterface`.

Please note that it is not intended to make runtime objects available, just types and constants. But that might still be valuable information for certain applications.

Feedback welcome.

**Comment by algernon** [comment]
Sketch-exploration sounds much more useful than keymap exploration. Keymap exploration sounds very good on paper too, but there's a big catch: keymaps can also reside in EEPROM, and `Layer.getKey()` can be overridden at run-time too. Both of these make any compile-time keymap exploration not very useful. You'd be limited to the built-in keymap only, which is useful in some cases, but... pretty much none of our existing plugins could take advantage of this feature.

Now, sketch exploration, that's much more interesting. There's a whole lot more there at compile-time that we can work with.

I do love this PR nevertheless! It was incredibly fun and educational to read it and wrap my head around it, and I was sad when it occurred to me that exploring keymaps at compile time isn't as useful as one might first think. But with expanding the scope to sketch exploration... oh, heck, yes, please.

**Comment by noseglasses** [comment]
Alright. I will see what i can do.

**Comment by noseglasses** [comment]
i now implemented sketch exploration that comprises the static keymap and registered plugins. Please see the example sketch for a demonstration of the exploration API: https://github.com/keyboardio/Kaleidoscope/pull/735/files#diff-c823ca2e2a17147da1c30151e2bfcb1b

If you have wishes regarding additional features of the API, let me know.

@algernon, I am not all that pessimistic about the benefit of exploring the static keymap. 
Plugins who need to check the (current) keymap can now conditionally checking the EEPROM keymap only if they found the EEPROM-Keymap plugin being registered. Otherwise they could live with the information they find in the static keymap. That theoretically provides room for optimization. But of course, up to now we don't have such plugins...

**Comment by noseglasses** [comment]
When working on this, I had to deal with problems that arise from naming plugin global instances the same way as their types. 

The following [example](https://godbolt.org/z/bFR5p3) demonstrates the problem.

I suggest at least for new plugins and other classes that require global instances to use a slightly different name for the type, e.g. by appending one or several underscores to the type name. 

```cpp
namespace kaleidoscope {
    class Foo {};
}

kaleidoscope::Foo Foo;

template<typename _T>
auto f(const _T &t) -> _T { return t; }

void g1() {
   // Works
   auto tmp = f(Foo);
}

namespace kaleidoscope {
    void g2() {
        // This fails because the compiler finds type kaleidoscope::Foo
        // but not instance ::Foo as one would expect. This is because of C++'s 
        // scoping rules.
        //
        auto tmp = f(Foo);
    }

    void g3() {
        // This works.
        //
        auto tmp = f(::Foo);
    }
}
```

**Comment by obra** [comment]
This is some deep and scary magic I don't fully understand. But I sort of understand what it gets you :)
I'm happy to merge it, though I'd love to see more documentation for it in the future

**Comment by algernon** [comment]
This broke the Raise:

```
In file included from /home/algernon/Arduino/hardware/dygma/samd/libraries/Kaleidoscope/src/kaleidoscope_internal/sketch_exploration/plugin_explora
tion.h:19:0,                                                                                                                                       
                 from /home/algernon/Arduino/hardware/dygma/samd/libraries/Kaleidoscope/src/kaleidoscope_internal/sketch_exploration/sketch_explora
tion.h:20,                                                                                                                                         
                 from /home/algernon/Arduino/hardware/dygma/samd/libraries/Kaleidoscope/src/kaleidoscope/layers.h:24,                              
                 from /home/algernon/Arduino/hardware/dygma/samd/libraries/Kaleidoscope/src/kaleidoscope/Kaleidoscope.h:61,                        
                 from /home/algernon/Arduino/hardware/dygma/samd/libraries/Kaleidoscope/src/Kaleidoscope.h:19,                                     
                 from /tmp/arduino-sketch-5536640E1ED0BA7E13F213ADD163654B/sketch/RaiseIdleLEDs.h:40,                                              
                 from /tmp/arduino-sketch-5536640E1ED0BA7E13F213ADD163654B/sketch/RaiseIdleLEDs.cpp:20:                                            
/home/algernon/Arduino/hardware/dygma/samd/libraries/Kaleidoscope/src/kaleidoscope_internal/type_traits/type_traits:50:18: error: conflicting decla
ration 'typedef void* std::nullptr_t'                                                                                                              
    typedef void* nullptr_t;                                                                                                                       
                  ^                                                                                                                                
In file included from /home/algernon/.arduino15/packages/arduino/tools/arm-none-eabi-gcc/4.8.3-2014q1/arm-none-eabi/include/c++/4.8.3/cstddef:41:0,
                 from /home/algernon/Arduino/hardware/dygma/samd/cores/arduino/Uart.h:25,
                 from /home/algernon/Arduino/hardware/dygma/samd/variants/arduino_zero/variant.h:43,
                 from /home/algernon/Arduino/hardware/dygma/samd/cores/arduino/delay.h:23,
                 from /home/algernon/Arduino/hardware/dygma/samd/cores/arduino/Arduino.h:81,
                 from /home/algernon/Arduino/hardware/dygma/samd/libraries/Kaleidoscope/src/kaleidoscope/Kaleidoscope.h:19,
                 from /home/algernon/Arduino/hardware/dygma/samd/libraries/Kaleidoscope/src/Kaleidoscope.h:19,
                 from /tmp/arduino-sketch-5536640E1ED0BA7E13F213ADD163654B/sketch/RaiseIdleLEDs.h:40,
                 from /tmp/arduino-sketch-5536640E1ED0BA7E13F213ADD163654B/sketch/RaiseIdleLEDs.cpp:20:
/home/algernon/.arduino15/packages/arduino/tools/arm-none-eabi-gcc/4.8.3-2014q1/arm-none-eabi/include/c++/4.8.3/arm-none-eabi/armv6-m/bits/c++confi
g.h:190:29: error: 'std::nullptr_t' has a previous declaration as 'typedefstd::nullptr_t std::nullptr_t'
   typedef decltype(nullptr) nullptr_t;
```

...and:

```
In file included from /home/algernon/Arduino/hardware/dygma/samd/libraries/Kaleidoscope/src/kaleidoscope/Kaleidoscope.h:61:0,
                 from /home/algernon/Arduino/hardware/dygma/samd/libraries/Kaleidoscope/src/Kaleidoscope.h:19,
                 from /home/algernon/src/dygma/ArduinoCore-samd/libraries/Raise-Firmware/Raise-Firmware.ino:18:
/home/algernon/Arduino/hardware/dygma/samd/libraries/Kaleidoscope/src/kaleidoscope/layers.h:30:122: error: redeclaration 'keymaps_linear' differs i
n 'constexpr'
   constexpr Key keymaps_linear[][kaleidoscope_internal::device.matrix_rows * kaleidoscope_internal::device.matrix_columns] PROGMEM = { layers };
         __NL__ \
                                                                                                                          ^
/home/algernon/src/dygma/ArduinoCore-samd/libraries/Raise-Firmware/Raise-Firmware.ino:113:1: note: in expansion of macro 'KEYMAPS'
 KEYMAPS(
 ^
In file included from /home/algernon/Arduino/hardware/dygma/samd/libraries/Kaleidoscope/src/kaleidoscope/layers.h:21:0,
                 from /home/algernon/Arduino/hardware/dygma/samd/libraries/Kaleidoscope/src/kaleidoscope/Kaleidoscope.h:61,
                 from /home/algernon/Arduino/hardware/dygma/samd/libraries/Kaleidoscope/src/Kaleidoscope.h:19,
                 from /home/algernon/src/dygma/ArduinoCore-samd/libraries/Raise-Firmware/Raise-Firmware.ino:18:
/home/algernon/Arduino/hardware/dygma/samd/libraries/Kaleidoscope/src/kaleidoscope/keymaps.h:21:18: error: from previous declaration 'keymaps_linear'
 extern const Key keymaps_linear[][kaleidoscope_internal::device.matrix_rows * kaleidoscope_internal::device.matrix_columns];
```

The latter might be the virtual fixes though. I saw that the other device plugins had to have headers rearranged, which I haven't done for the Raise yet.

**Comment by algernon** [comment]
Reverting 686044264e8815ffd1bf769e52e6ae6318753102, 7aa2c0e8596bd18412990067ebb5ee2ac6902f84 and a538328ba2f702595abb3b203868942467cf83b5 appears to fix the problem. Haven't narrowed it down further yet.

**Comment by algernon** [comment]
The type traits I can fix easily, by adding an `#ifdef __AVR__` guard against the nullptr line in our version of `type_traits`.

**Comment by noseglasses** [comment]
This is something I just stumbled upon two minutes ago when I was building virutual Kaleidoscope with clang-8.

I guess the first error is not connected to this PR. It emerges due to the fact that you probably use a different compiler than avr-gcc for the Raise. It likely comes with a different version of the standard library than avr-gcc 5.4. This results in a mixture of stuff from the compiler's stdlib and our type_traits header shipped with Kaleidoscope. I'll submit a PR in a minute.

The second problem is not that obvious but I have seen it before...let me think about it further.

**Comment by noseglasses** [comment]
Here's a PR https://github.com/keyboardio/Kaleidoscope/pull/739 that deals with the type traits issue. It modifies the include behavior in a way that Kaleidoscope's version of type_traits is only used for AVR builds and the system version preferred otherwise. That solves the problems with x86 builds where header `type_traits` is available. Not sure if arm-gcc has it. If not, your solution sounds reasonable.

**Comment by noseglasses** [comment]
I see that you build with gcc 4.8.3 on arm. That may explain the difference to my avr builds with gcc 5.4. The problem is that `extern` and `constexpr` may not be combined (because that makes no sense) but appear to be accepted by some compilers. Not 100% what the standard says about it.

**Comment by noseglasses** [comment]
BTW, making the keymap array constexpr is part of the sketch exploration stuff. It is necessary to enable compile time access to the keymap.

I am currently experimenting with different compiler versions for the virtual and physical builds, to make Kaleidoscope fit for being build with future compilers (now as there are new versions of avr-gcc around).

**Comment by noseglasses** [comment]
This really seems to be a problem with gcc 4.8.x, see [an example](https://www.godbolt.org/z/hER2G7). With later versions starting from 5.x it does not cause any trouble.

Do you have a later version of arm-gcc available? What are the typical compiler versions that are shipped with current Arduino for arm?

**Comment by algernon** [comment]
The latest for the SAMD core is `7-2017q4`. That gets me different issues:

```
/home/algernon/Arduino/hardware/dygma/samd/libraries/Kaleidoscope/src/kaleidoscope/util/flasher/Base.h:32:30: error: static data member 'kaleidoscope::util::flasher::BaseProps::<unnamed struct>::page_address' in unnamed class [-fpermissive]                                                      
     static constexpr uint8_t page_address = 0x01;
```

And a few like that, but those I can fix (already did, PR pending). So the solution appears to be to update arm-gcc, which we can do.

Thanks for the help!
